### PR TITLE
Geometry point data

### LINKED ISSUE #163: Support coloring by scalar attributes (point or cell data) on geometries
@banesullivan

### PR DESCRIPTION
**Pull request by thewtex**
@banesullivan 

Closes #163

### CODE REVIEW

**Comment by banesullivan** [comment]
This is awesome!! 🚀 

Now how do I use it? 😀

**Comment by thewtex** [comment]
@banesullivan release coming soon :-)

**Comment by banesullivan** [comment]
I already cloned as soon as I saw this 😀  and got it working!!!!

```py
import pyvista as pv
from pyvista import examples

from itkwidgets import view

mesh = examples.download_st_helens().warp_by_scalar().extract_geometry()

view(geometries=mesh)
```

Screen Shot 2019-07-23 at 1 01 59 PM



This is so awesome!!!!

is there a way to specify to colormap to use when plotting it?

**Comment by banesullivan** [comment]
or perhaps could Viridis be the default colormap?

**Comment by banesullivan** [comment]
well, there is the `cmap` argument to the `view` function that I am aware of but how might I control the colormap for individual geometries programmatically?

I.e. how would I specify a colormap when implementing a plotter like https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/154#issuecomment-509916931

```py
class PlotterITK():
    def __init__(self, **kwargs):
        self.plotter = Viewer()
        
    def add_mesh(self, mesh, **kwargs):
        """Adds mesh to the scene"""
        mesh = mesh.extract_geometry()
        self.plotter.geometries.append(mesh)
        # do something with the colormap argument:
        cmap = kwargs.get('cmap')
        
    def show(self, **kwargs):
        """Show in cell output"""
        return self.plotter
    
plotter = PlotterITK()
plotter.add_mesh(mesh, cmap='viridis')
plotter.show()
```

**Comment by thewtex** [comment]
> I already cloned as soon as I saw this  and got it working!!!!
> 
> ```python
> import pyvista as pv
> from pyvista import examples
> 
> from itkwidgets import view
> 
> mesh = examples.download_st_helens().warp_by_scalar().extract_geometry()
> 
> view(geometries=mesh)
> ```
> 
> Screen Shot 2019-07-23 at 1 01 59 PM

Very awesome @banesullivan ! :1st_place_medal: :taco:

**Comment by thewtex** [comment]
> is there a way to specify to colormap to use when plotting it?

Not yet -- coming, though. Tracking in #174 

> or perhaps could Viridis be the default colormap?

Yes, we could do that. :+1: 

> well, there is the cmap argument to the view function

`cmap` is applied to the `image`.

**Pull request merged**
