### PR TITLE
ENH: Add support for creating a video recording

### PR DESCRIPTION
**Pull request by thewtex**
@maartenbreddels bringing the awesome capabilities of `ipywebrtc`! :battery:

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Great, FYI, the next version allows to turn any widget into a MediaStream if you don't want to depend on ipywebrtc, see https://github.com/maartenbreddels/ipywebrtc/pull/5
cc @martinRenou

**Comment by thewtex** [comment]
@maartenbreddels @martinRenou cool!

**Comment by maartenbreddels** [comment]
Master now had a MediaImageRecorder for making screenshots, would be great
if you can try it out. We want to release it soon.

(from mobile phone)

**Comment by thewtex** [comment]
@maartenbreddels @martinRenou fantastic!

Tested and added to an example here:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/64

Fix found for `ipywebrtc` here:

https://github.com/maartenbreddels/ipywebrtc/pull/10

**Pull request merged**
