### PR TITLE
Pyvista unstructured grid example

### PR DESCRIPTION
**Pull request by thewtex**
@banesullivan please take a look.

@jourdain any thoughts or tips here?

### CODE REVIEW

**Comment by banesullivan** [comment]
Why just `vtkUnstructuredGrid`?:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/cf33dad9082965aeca9b21767c53f0474dae38e8/itkwidgets/_transform_types.py#L297

Why not everything besides `vtkImageData`? That way all VTK and PyVista types could easily be passed? E.g.:

```py
elif have_vtk and isinstance(geometry_like, (vtk.vtkUnstructuredGrid, 
                    vtk.vtkStructuredGrid, 
                    vtk.vtkRectilinearGrid)):
```

**Comment by banesullivan** [comment]
Also there are flashier datasets than the hexbeam:

```py
import pyvista as pv
from pyvista import examples
from itkwidgets import view
import os

try:
    from urllib.request import urlretrieve
except ImportError:
    from urllib import urlretrieve
```
```py
# Download data
file_name = 'uGridEx.vtk'
if not os.path.exists(file_name):
    url = 'https://data.kitware.com/api/v1/file/5d3752c2877dfcc9022724d9/download'
    urlretrieve(url, file_name)
    
mesh = pv.read(file_name)
view(geometries=mesh)
```

Screen Shot 2019-07-25 at 6 36 16 PM


PolyData
```py
mesh = examples.download_nefertiti()
view(geometries=mesh)
```

Screen Shot 2019-07-25 at 6 29 52 PM


StructuredGrid
```py
mesh = examples.download_st_helens().warp_by_scalar().extract_geometry()
view(geometries=mesh)
```

Screen Shot 2019-07-25 at 6 31 59 PM


And heres another unstrucured grid but it throws an error when trying to view it... looks like something with the vtkjs mapping

```py
mesh = examples.load_channels().threshold([2,5])
import vtk
print(isinstance(mesh, vtk.vtkUnstructuredGrid))
view(geometries=mesh)
```

Traceback: <details/>

```
ERROR:root:
UnicodeDecodeError while processing traceback.

ERROR:root:
UnicodeDecodeError while processing traceback.

True
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/Documents/OpenGeoVis/External/itk-jupyter-widgets/itkwidgets/trait_types.py in validate(self, obj, value)
    271                 if not isinstance(geometry, dict) or not 'vtkClass' in geometry:
--> 272                     geometries[index] = to_geometry(geometry)
    273             return geometries

~/Documents/OpenGeoVis/External/itk-jupyter-widgets/itkwidgets/_transform_types.py in to_geometry(geometry_like)
    300         geometry_filter.Update()
--> 301         geometry = to_geometry(geometry_filter.GetOutput())
    302         return geometry

~/Documents/OpenGeoVis/External/itk-jupyter-widgets/itkwidgets/_transform_types.py in to_geometry(geometry_like)
    271                     'size': vtk_array.GetSize(),
--> 272                     'dataType': _vtk_data_type_to_vtkjs_type[vtk_array.GetDataType()],
    273                     'values': vtk_to_numpy(vtk_array) } }

KeyError: 8

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2038                         # in the engines. This should return a list of strings.
-> 2039                         stb = value._render_traceback_()
   2040                     except Exception:

AttributeError: 'TraitError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3340             if result is not None:
   3341                 result.error_in_exec = sys.exc_info()[1]
-> 3342             self.showtraceback(running_compiled_code=True)
   3343         else:
   3344             outflag = False

~/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2040                     except Exception:
   2041                         stb = self.InteractiveTB.structured_traceback(etype,
-> 2042                                             value, tb, tb_offset=tb_offset)
   2043 
   2044                     self._showtraceback(etype, value, stb)

~/.local/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1383         self.tb = tb
   1384         return FormattedTB.structured_traceback(
-> 1385             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1386 
   1387 

~/.local/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1286             # Verbose modes need a full traceback
   1287             return VerboseTB.structured_traceback(
-> 1288                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1289             )
   1290         elif mode == 'Minimal':

~/.local/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1148         exception = self.get_parts_of_chained_exception(evalue)
   1149         if exception:
-> 1150             formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)
   1151             etype, evalue, etb = exception
   1152         else:

TypeError: can only concatenate str (not "list") to str

```
</details>


But it would look something like:

download

**Comment by jourdain** [comment]
@banesullivan I think you need to extract_geometry() on your unstructuredGrid unless it is supposed to happen automatically? (@thewtex ?)

Otherwise a quick glimpse through the code seems fine to me. @thewtex what were you curious about from my end? Feel free to call me today, I'm still in NY, so we have the same time zone...

**Comment by banesullivan** [comment]
> @banesullivan I think you need to `extract_geometry()` on your unstructuredGrid unless it is supposed to happen automatically? (@thewtex ?)

We shouldn't need it because of:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/cf33dad9082965aeca9b21767c53f0474dae38e8/itkwidgets/_transform_types.py#L297-L302

which applies the `vtkGeometryFilter` to make unstrucured grids possible in this PR. If I do apply PyVista's equivalent of this, `extract_geometry()`, I still get the error which is due to having `int64` value in the cell data of this mesh. If I cast those values to `int32` then all is good:

```py
...
mesh = examples.load_channels().threshold([2,5]).extract_geometry()
import vtk, numpy as np
assert isinstance(mesh, vtk.vtkPolyData)
assert mesh['facies'].dtype == np.int64
mesh['facies'] = mesh['facies'].astype(np.int32)
view(geometries=mesh)
```
(same traceback)

@thewtex: can you fix issues with `int64` values?

**Comment by thewtex** [comment]
@banesullivan fantastic suggestions -- we'll add these!

@jourdain thanks for the thoughts. I was wondering if you take a similar approach when encountering 64 bit integer data array. Glad to hear you are back in The States. I am in Long Island visiting family, but I will be back on Monday.

**Comment by jourdain** [comment]
Yes I do use the same approach converting the int to something manageable on the JS side.

**Comment by thewtex** [comment]
> Why just `vtkUnstructuredGrid`?:
> 
> https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/cf33dad9082965aeca9b21767c53f0474dae38e8/itkwidgets/_transform_types.py#L297
> 
> Why not everything besides `vtkImageData`? That way all VTK and PyVista types could easily be passed? E.g.:
> 
> ```python
> elif have_vtk and isinstance(geometry_like, (vtk.vtkUnstructuredGrid, 
>                     vtk.vtkStructuredGrid, 
>                     vtk.vtkRectilinearGrid)):
> ```

Addressed in #178

**Comment by thewtex** [comment]
> file_name = 'uGridEx.vtk'

Since this is already in a VTK example, I'll use others for variety.

> mesh = examples.download_nefertiti()

Nice! Appended to the *pyvista.PolyData* example.

> mesh = examples.download_st_helens().warp_by_scalar()

Awesome! Added to a new *pyvista.StructuredGrid* example. :rocket: :guitar: 

> mesh = examples.load_channels().threshold([2,5])

> But it would look something like:

Fix added and appended to the *pyvista.StructuredGrid* example.

image

**Pull request merged**
